name: Go Build and Test
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test chain
    permissions:
      contents: read
      checks: write
    defaults:
      run:
        working-directory: ./inference-chain
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '1.24.2' # Replace with your Go version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone cosmos-sdk repo with specific branch
        run: |
          git clone --branch release/v0.50.x https://github.com/product-science/cosmos-sdk.git ../../ps-fork/cosmos-sdk

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o ./build/inferenced ./cmd/inferenced/main.go

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Run Tests and Generate JUnit Report
        run: go test ./... -v 2>&1 | go-junit-report -set-exit-code > junit-report.xml

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: node-junit-report
          path: inference-chain/junit-report.xml

      - name: Report Test Results in GitHub
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Inferenced Tests
          path: inference-chain/junit-report.xml
          reporter: java-junit
  build-and-test-api:
    runs-on: ubuntu-latest
    name: Build and Test API Wrapper
    permissions:
      contents: read
      checks: write
    defaults:
      run:
        working-directory: ./decentralized-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone cosmos-sdk repo with specific branch
        run: |
          git clone --branch release/v0.50.x https://github.com/product-science/cosmos-sdk.git ../../ps-fork/cosmos-sdk

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.2' # Replace with your Go version

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report@latest

      - name: Run Tests and Generate JUnit Report
        run: go test ./... -v 2>&1 | go-junit-report -set-exit-code > junit-report.xml

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-junit-report
          path: decentralized-api/junit-report.xml

      - name: Report Test Results in GitHub
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Decentralized-API Tests
          path: decentralized-api/junit-report.xml
          reporter: java-junit
